name: demologin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  country_picker: ^2.0.27
  flutter_otp_text_field: ^1.5.1+1
  lottie: ^3.3.1
  flutter_image_slideshow: ^0.1.6
  flutter_svg: ^2.0.17
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  smooth_page_indicator: ^1.2.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.9
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/image/jerry.jpg"
    - "assets/image/o-removebg.png"
    - "assets/image/verification-removebg.png"
    - "assets/image/otp_success.json"
    - "assets/image/boyss.jpg"
    - "assets/image/winter1.jpg"
    - "assets/image/winter2.jpg"
    - "assets/image/summer.jpg"
    - "assets/image/airpods.jpg"
    - "assets/image/shoe.jpg"
    - "assets/image/watches.jpg"
    - "assets/image/phones.jpg"
    - "assets/image/shirt.jpg"
    - "assets/image/jacket.jpg"
    - "assets/image/tv.jpg"
    - "assets/image/shoeback.jpg"
    - "assets/image/location-1.svg"
    - "assets/image/clock.png"
    - "assets/image/paypal.svg"
    - "assets/image/creditcard.svg"
    - "assets/image/cash.svg"
    - "assets/image/logg.png"
    - "assets/image/watchess.jpg"
    - "assets/image/map.jpg"
    - "assets/image/map1.jpg"
    - "assets/image/reward.jpg"
    - "assets/image/qualityproduct.jpg"
    - "assets/image/fastdelivery.jpg"
    - "assets/image/flutter.png"
    - "assets/image/instagram1.jpg"
    - "assets/image/ecommerecicon.jpg"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/ecommerecicon.jpg"





