// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA62DrW6L8ATW8EJTEIooKxmhyNahkURNU',
    appId: '1:193336111230:web:c5fa395dbd0840ba04e82f',
    messagingSenderId: '193336111230',
    projectId: 'demologin-21346',
    authDomain: 'demologin-21346.firebaseapp.com',
    storageBucket: 'demologin-21346.firebasestorage.app',
    measurementId: 'G-721806LKP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT1tVo5IgPS-IM0IqRprwuowZypw0GkMg',
    appId: '1:193336111230:android:13c7ee06e76db18704e82f',
    messagingSenderId: '193336111230',
    projectId: 'demologin-21346',
    storageBucket: 'demologin-21346.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhpWPF-1YQXHlC62yHw1WFOV4Xtb2fMQc',
    appId: '1:193336111230:ios:ae9afe7ec2697feb04e82f',
    messagingSenderId: '193336111230',
    projectId: 'demologin-21346',
    storageBucket: 'demologin-21346.firebasestorage.app',
    iosBundleId: 'com.example.demologin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhpWPF-1YQXHlC62yHw1WFOV4Xtb2fMQc',
    appId: '1:193336111230:ios:ae9afe7ec2697feb04e82f',
    messagingSenderId: '193336111230',
    projectId: 'demologin-21346',
    storageBucket: 'demologin-21346.firebasestorage.app',
    iosBundleId: 'com.example.demologin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA62DrW6L8ATW8EJTEIooKxmhyNahkURNU',
    appId: '1:193336111230:web:1a9bde579e797ba604e82f',
    messagingSenderId: '193336111230',
    projectId: 'demologin-21346',
    authDomain: 'demologin-21346.firebaseapp.com',
    storageBucket: 'demologin-21346.firebasestorage.app',
    measurementId: 'G-G647VJ5QDX',
  );
}
